vich_uploader:
    db_driver: orm

    mappings:
        materiel:
            uri_prefix: /images/materiel
            upload_destination: '%kernel.project_dir%/public/images/materiel'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
